name: Build and Test

on:
  push:

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1.6.3

      - name: Install OpenCppCoverage
        run: |
          $url = "https://github.com/OpenCppCoverage/OpenCppCoverage/releases/download/release-0.9.9.0/OpenCppCoverageSetup-x64-0.9.9.0.exe"
          $output = "OpenCppCoverageSetup.exe"
          Invoke-WebRequest -Uri $url -OutFile $output
          Start-Process -FilePath $output -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-" -Wait

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build (MSVC)
        uses: lukka/run-cmake@v10
        env:
          CMAKE_TOOLCHAIN_FILE: ${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake
          LLVM_PATH: ${{ env.PROGRAMFILES}}/LLVM/bin/
        with:
          workflowPreset: x64-Debug-MSVC

      - name: Build (Clang)
        uses: lukka/run-cmake@v10
        env:
          CMAKE_TOOLCHAIN_FILE: ${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake
          LLVM_PATH: ${{ env.PROGRAMFILES}}/LLVM/bin/
        with:
          workflowPreset: x64-Debug-Clang

      - name: Run Unit Tests
        run: >
          "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe"
          --working_dir "${{ github.workspace }}/out/x64-Debug-MSVC"
          --export_type "cobertura:${{ github.workspace }}/out/x64-Debug-MSVC/raw_coverage.xml"
          --cover_children
          --sources "${{ github.workspace }}"
          -- ctest -j --verbose -T Test

      - name: Analyze (cppcheck)
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          other_options: >
            --xml
            --project="${{ github.workspace }}/out/x64-Debug-MSVC/hello.sln"
            --project-configuration=Debug|x64
            -D__cppcheck__