name: Build and Test

on:
  push

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - uses: ssciwr/doxygen-install@v1.6.3
      - uses: sigoden/install-binary@v1
        with:
          repo: OpenCppCoverage/OpenCppCoverage
          tag: release-0.9.9.0
          name: OpenCppCoverageSetup-x64-0.9.9.0.exe
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: lukka/run-cmake@v10
        env:
          CMAKE_TOOLCHAIN_FILE: "${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake"
          LLVM_PATH: "${{ env.PROGRAMFILES }}/LLVM/bin/"
        with:
          workflowPreset: x64-Debug-MSVC
      - uses: lukka/run-cmake@v10
        env:
          CMAKE_TOOLCHAIN_FILE: "${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake"
          LLVM_PATH: "${{ env.PROGRAMFILES }}/LLVM/bin/"
        with:
          workflowPreset: x64-Debug-Clang
      - run: OpenCppCoverage |
          --working_dir "${{ GITHUB_WORKSPACE }}/out/x64-Debug-MSVC" |
          --export_type "cobertura:${{ GITHUB_WORKSPACE }}/out/x64-Debug-MSVC/raw_coverage.xml" |
          --cover_children |
          --sources "${{ GITHUB_WORKSPACE }}"
          -- ctest -j --verbose -T Test
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          other_options: --xml |
              --project="${{ GITHUB_WORKSPACE }}/out/x64-Debug-MSVC/hello.sln" |
              --project-configuration=Debug|x64 |
              -D__cppcheck__